version: "3"

services:

  restapi:
    build:
      context: ../../
      dockerfile: docker/files/restapi.dockerfile
    container_name: restapi
    ports:
      - 4000:4000
    depends_on: 
      - server-database
    environment:
      - DEBUG=msm-main:*,datalayer:*
      - NODE_ENV=dock-dev
    
  server-database:
    image: mongo:4.2.24-rc2-bionic
    ports:
      - 27017:27017