version: "3"

services:

  restapi:
    build:
      context: ../../
      dockerfile: docker/files/restapi.dockerfile
    container_name: restapi
    ports:
      - 4000:4000
    depends_on: 
      - server-database
    environment:
      - DEBUG=msm-main:*,datalayer:*
      - NODE_ENV=dock-dev
    
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: server-database
    ports:
      - "8000:8000"