AWSTemplateFormatVersion: 2010-09-09
Description: >
  Resources needed to deploy a scheduled lambda function.

####################################################################################
Resources:
####################################################################################

  MSMCleanupManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudwatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:CreateLogGroup
              - logs:PutLogEvents
            Resource:
              - "*"
          - Sid: DynamoDBIndexAndStreamAccess
            Effect: Allow
            Action:
              - dynamodb:GetShardIterator
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
            Resource:
              - arn:aws:dynamodb:eu-west-3:914445634489:table/BetaMSMTable/index/*
              - arn:aws:dynamodb:eu-west-3:914445634489:table/BetaMSMTable/stream/*
          - Sid: DynamoDBTableAccess
            Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:PutItem
              - dynamodb:DescribeTable
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
            Resource: arn:aws:dynamodb:eu-west-3:914445634489:table/BetaMSMTable

  MSMCleanupRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref MSMCleanupManagedPolicy

  MSMCleanupSchedule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: >
        A schedule for the Lambda function..
      ScheduleExpression: "rate(1 day)"
      State: ENABLED
      Targets:
        - Arn: !Sub ${MSMCleanupLambdaFunction.Arn}
          Id: MSMCleanupSchedule

  MSMCleanupSchedulePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub ${MSMCleanupLambdaFunction.Arn}
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub ${MSMCleanupSchedule.Arn}

  MSMCleanupLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      PackageType: Image
      Code:
        ImageUri: "914445634489.dkr.ecr.eu-west-3.amazonaws.com/cantlose:mft-msm-cleanup.beta.1"
      MemorySize: 128
      Role: !Sub ${MSMCleanupRole.Arn}
      Environment:
        Variables:
          NODE_ENV: "staging"
          KEY_REPORT_AT: "mat"
          DEBUG: "msm-cleanup:*,dynamolayer:*"
