AWSTemplateFormatVersion: 2010-09-09
Description: Deploy the whole MSM stack

####################################################################################
Parameters:
####################################################################################

  MSMStageName:
    Type: String
    Default: test
    Description: The name of the stage to be created, also used as NODE_ENV

  MSMTableName:
    Type: String
    Default: TestTableMSM
    Description: The name of the table to be created.

  MSMSecretName:
    Type: String
    Default: test
    Description: The name of the secret to use.

  MSMSecretID:
    Type: String
    Default: test
    Description: The id of the secret to use.

  MSMHttpApiDomainName:
    Type: String
    Default: test.ysypya.com
    Description: API Domain name

  MSMWssApiDomainName:
    Type: String
    Default: socktest.ysypya.com
    Description: API Domain name

  MSMHttpApiCertificateID:
    Type: String
    Description: The ID of the certificate for the domain.

  MSMWssApiCertificateID:
    Type: String
    Description: The ID of the certificate for the domain.

  MSMHostedZoneID:
    Type: String
    Description: The ID of the hosted zone

  MSMImageTag:
    Type: String
    Default: latest
    Description: The ID of the hosted zone

  MSMMainProvisionedNumber:
    Type: Number
    Default: 0
    Description: The number of provisioned lambda functions for main

####################################################################################
Resources:
####################################################################################

  MSMCleanupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_cleanup_formation.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        DailyCleanupImageName: !Sub 'mft-msm-clean-daily.${MSMStageName}.${MSMImageTag}'
        AccountCleanupImageName: !Sub 'mft-msm-clean-account.${MSMStageName}.${MSMImageTag}'
        MessageCleanupImageName: !Sub 'mft-msm-clean-message.${MSMStageName}.${MSMImageTag}'
        SchedulerGroupName: !Sub '${MSMStageName}-MSM-Cleanup-Group'

  MSMWssAPIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_wss_api_template.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        MSMSecretName: !Ref MSMSecretName
        ConnectHandlerImageName: !Sub 'mft-msm-ws-connect.${MSMStageName}.${MSMImageTag}'
        DisconnectHandlerImageName: !Sub 'mft-msm-ws-disconnect.${MSMStageName}.${MSMImageTag}'
        FallbackHandlerImageName: !Sub 'mft-msm-ws-fallback.${MSMStageName}.${MSMImageTag}'
        MSMApiDomainName: !Ref MSMWssApiDomainName
        MSMApiCertificateID: !Ref MSMWssApiCertificateID
        MSMHostedZoneID: !Ref MSMHostedZoneID
        MSMSecretID: !Ref MSMSecretID

  MSMNotifiedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_notification_formation.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        MSMSecretName: !Ref MSMSecretName
        NotificationImageName: !Sub 'mft-msm-notification.${MSMStageName}.${MSMImageTag}'
        MSMAPIId: !GetAtt MSMWssAPIStack.Outputs.APIId
        MSMNotificationTopicName: !Sub '${MSMStageName}MsmNotifTopic'
        MSMSecretID: !Ref MSMSecretID

  MSMValidateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_validate_formation.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        MSMSecretName: !Ref MSMSecretName
        ValidationImageName: !Sub 'mft-msm-validation.${MSMStageName}.${MSMImageTag}'
        MSMValidationTopicName: !Sub '${MSMStageName}MsmValidateTopic'
        SchedulerGroupName: !Sub '${MSMStageName}-MSM-Confirmation-Group'
        MSMSecretID: !Ref MSMSecretID

  MSMMarkReadStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_message_read_formation.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        MarkReadLambdaImageName: !Sub 'mft-msm-mark-read.${MSMStageName}.${MSMImageTag}'
        MSMValidateTopicName: !GetAtt MSMValidateStack.Outputs.ValidateTopicEndpoint
        MSMSchedulerGroupName: !GetAtt MSMCleanupStack.Outputs.GroupName
        MSMCleanMessageLambda: !GetAtt MSMCleanupStack.Outputs.MessageCleanupName
        MSMCleanupSchedulerRole: !GetAtt MSMCleanupStack.Outputs.SchedulerRoleName

  MSMMainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://msm-cloudformation-template.s3.eu-west-3.amazonaws.com/msm_main_formation.yaml
      Parameters:
        MSMStageName: !Ref MSMStageName
        MSMTableName: !Ref MSMTableName
        MSMSecretName: !Ref MSMSecretName
        MSMApiDomainName: !Ref MSMHttpApiDomainName
        MSMApiCertificateID: !Ref MSMHttpApiCertificateID
        MSMHostedZoneID: !Ref MSMHostedZoneID
        MSMMainProvisionedNumber: !Ref MSMMainProvisionedNumber
        MSMTagName: !Ref MSMImageTag
        MSMLambdaImageName: !Sub 'mft-msm-main.${MSMStageName}.${MSMImageTag}'
        MSMNotifTopicName: !GetAtt MSMNotifiedStack.Outputs.NotifyTopicEndpoint
        MSMSchedulerGroupName: !GetAtt MSMCleanupStack.Outputs.GroupName
        MSMCleanAccountLambda: !GetAtt MSMCleanupStack.Outputs.AccountCleanupName
        MSMCleanupSchedulerRole: !GetAtt MSMCleanupStack.Outputs.SchedulerRoleName
        MSMSecretID: !Ref MSMSecretID
        MSMMarkReadQueueName: !GetAtt MSMMarkReadStack.Outputs.MarkReadQueueName
        MSMMarkReadQueueURL: !GetAtt MSMMarkReadStack.Outputs.MarkReadQueueURL